services:
    fastapi_app:
        build: .
        ports:
            - "8111:8111"
        depends_on:
            - redis
        command: uvicorn main:app --host 0.0.0.0 --port 8111
    redis:
        image: "redis:alpine"
        ports:
            - "6380:6380"
        command: ["redis-server", "--port", "6380"]
